# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0a3c7aed79ffa498aaafaf2dfe4f2a34975d1c715c3956c09ad5a0e6dba4be3f3ad291e0b4dc3c5827ee189bc70d456f2718ebffd43568f20aca7b78c2db146f

test:
  secret_key_base: 72f6d1891de68e06672705e7cc39d39e00a5c6d3be45d857804e4d8ca09e70f61b48f6521904a4cd93e3d71913db18c8d8e07522fdc5d2da70c3a76b7d36cb87

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
